{% set name = "python-irodsclient" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-irodsclient-{{ version }}.tar.gz
  sha256: d1beddd377469a2bfce2ee019477c1b9af8d7597004187f6b357491d66e93da4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - defusedxml
    - prettytable >=0.7.2
    - python >={{ python_min }}
    - six >=1.10.0

test:
  imports:
    - irods
    - irods.manager
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/irods/python-irodsclient
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A python API for iRODS
  description: |
    iRODS is an open-source distributed data management system. This is a
    client API implemented in python.
  doc_url: https://github.com/irods/python-irodsclient
  dev_url: https://github.com/irods/python-irodsclient

extra:
  recipe-maintainers:
    - chrisburr
    - stolpeo
