{% set name = "python-irodsclient" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-irodsclient-{{ version }}.tar.gz
  sha256: cb06bc92024492afd8598dbda57a8b30d1e0153c3d4a145f8d5b3acfdc98ed03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.6
  run:
    - defusedxml
    - prettytable >=0.7.2
    - python =2.7|>=3.6
    - six >=1.10.0

test:
  imports:
    - irods
    - irods.manager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/irods/python-irodsclient
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A python API for iRODS
  description: |
    iRODS is an open-source distributed data management system. This is a
    client API implemented in python.
  doc_url: https://github.com/irods/python-irodsclient
  dev_url: https://github.com/irods/python-irodsclient

extra:
  recipe-maintainers:
    - chrisburr
    - stolpeo
