{% set name = "python-irodsclient" %}
{% set version = "0.8.3" %}
{% set sha256 = "5afb6105e4ed01ac40cc8c418d754d2058e1308ae90549fcde13a09d0fd27952" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six >=1.10.0
    - prettytable >=0.7.2
    - xmlrunner >=1.7.7

test:
  imports:
    - irods
    - irods.message
    - irods.manager

about:
  home: https://github.com/irods/python-irodsclient
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A python API for iRODS
  description: |
    iRODS is an open-source distributed data management system. This is a
    client API implemented in python.
  doc_url: https://github.com/irods/python-irodsclient
  dev_url: https://github.com/irods/python-irodsclient

extra:
  recipe-maintainers:
    - stolpeo
